name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ветка, с которой будет деплой

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3

      # Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./        # Корень репозитория, где лежит index.html
